java -jar "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\Java\WarThunderGroundAttackTestRangeGenerator\target\war-thunder-ground-attack-test-range-generator-1.3.0-jar-with-dependencies.jar" "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data"

xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_China.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_China_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_France.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_France_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_Germany.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_Germany_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_Israel.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_Israel_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_Italy.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_Italy_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_Japan.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_Japan_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_other.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_other_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_Sweden.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_Sweden_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_UK.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_UK_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_US.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_US_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_USSR.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Attack_Test_Range_USSR_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_China.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_China_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_China_screenshot.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_France.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_France_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_France_screenshot.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Germany.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Germany_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Germany_screenshot.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Israel.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Israel_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Israel_screenshot.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Italy.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Italy_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Italy_screenshot.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Japan.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Japan_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Japan_screenshot.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_other.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_other_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_other_screenshot.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Sweden.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Sweden_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_Sweden_screenshot.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_UK.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_UK_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_UK_screenshot.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_US.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_US_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_US_screenshot.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_USSR.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_USSR_qa.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
xcopy /Y "C:\jogo\War Thunder\MISSIONS\WarThunderMissionGroundForcesTestRange\data\Ground_Forces_Test_Range_USSR_screenshot.blk" C:\Users\GuilhermeAlanRitter\AppData\Local\WarThunder\UserMissions
