<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.github.guiritter</groupId>
  <artifactId>war-thunder-ground-attack-test-range-generator</artifactId> 
  <version>1.3.1</version> 
  <packaging>jar</packaging>

  <name>War Thunder Ground Attack Test Range Generator</name> 
  <description>Generates air and ground missions featuring all ground vehicles</description> 
  <url>https://github.com/GuiRitter/WarThunderMissionGroundForcesTestRange</url> 

  <licenses> 
    <license> 
      <name>MIT License</name> 
      <url>http://www.opensource.org/licenses/mit-license.php</url> 
    </license> 
  </licenses> 

  <developers> 
    <developer> 
      <name>Guilherme Alan Ritter</name> 
      <email>gui.a.ritter@gmail.com</email> 
    </developer> 
  </developers> 

  <properties> 
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding> 
    <maven.compiler.source>14</maven.compiler.source> 
    <maven.compiler.target>14</maven.compiler.target> 
    <exec.mainClass>io.github.guiritter.war_thunder.ground_attack_test_range_generator.MissionGenerator</exec.mainClass> 
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>[1.0.0,)</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
    
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.2</version>
        <configuration> <!-- Compile java 14 compatible bytecode -->
          <source>14</source>
          <target>14</target>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <archive>
              <manifest>
                <mainClass>io.github.guiritter.war_thunder.ground_attack_test_range_generator.MissionGenerator</mainClass>
              </manifest>
              </archive>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>  <!-- Create sources.jar -->
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>3.0.1</version> 
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
            
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.1.0</version> 
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
